# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

plugins:
  - jekyll-redirect-from
  - jekyll-paginate

pagenate: 3
pagenate_path: "/page/page:num/"

permalink: /:year/:month/:day/:title.html

timezone: Asia/Tokyo

title: Yuri Umemoto
logo: /pics/patapata.gif
description: Yuri Umemoto (b.2002) is a composer from Tokyo.
show_downloads: false
##google_analytics:
theme: minima
##theme: jekyll-theme-minimal

minima:
 date_format: "%-d %b %Y (%Y年 %m月 %d日)"
## social_links:
##  - {platform: twitter, user_url: "https://x.com/yuriumemoto"}
##  - {platform: youtube, user_url: "https://www.youtube.com/c/YuriUmemoto"}
##  - {platform: instagram, user_url: "https://www.instagram.com/yuri_umemoto"}

author:
 name: Yuri Umemoto, UMEMOTO LLC
 email: yuri@umemoto.org
 copyright: © Yuri Umemoto / UMEMOTO LLC, All Rights Reserved.
 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.yuriumemoto.com" # the base hostname & protocol for your site, e.g. http://example.com
 
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
